app/models.py
from . import db

class Imovel(db.Model):
    __tablename__ = 'Imoveis'

    id = db.Column(db.Integer, db.Identity(), primary_key = True)
    logradouro = db.Column(db.String())
    cep = db.Column(db.Integer())
    bairro = db.Column(db.String())
    cidade = db.Column(db.String())

    def __init__(self, id, logradouro, cep, bairro, cidade):
        self.id = id
        self.logradouro = logradouro
        self.cep = cep
        self.bairro = bairro
        self.cidade = cidade

    def __repr__(self):
        return f"<Imovel {self.logradouro}, {self.cidade}.>"

class Individuo(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    nome = db.Column(db.String())
    data_de_nascimento = db. Column(db.String())

    def __init__(self, id, nome, data_de_nascimento):
        self.id = id
        self.nome = nome
        self.data_de_nascimento = data_de_nascimento

    def __repr__(self):
        return f"<Individuo {self.id}: {self.nome}, nascida(o) em {self.data_de_nascimento}.>"

    
class Inquilino(db.Model):
    __tablename__ = 'Inquilinos'

    id = db.Column(db.Integer, primary_key = True)
    nome = db.Column(db.String())
    data_de_nascimento = db. Column(db.String())

    def __init__(self, id, nome, data_de_nascimento):
        self.id = id
        self.nome = nome
        self.data_de_nascimento = data_de_nascimento

    def __repr__(self):
        return f"<Proprietario {self.id}: {self.nome}, nascida(o) em {self.data_de_nascimento}>"

    
class Proprietario(db.Model):
    __tablename__ = 'Proprietarios'

    id = db.Column(db.Integer, primary_key = True)
    nome = db.Column(db.String())
    data_de_nascimento = db. Column(db.String())


    def __init__(self, id, nome, data_de_nascimento):
        self.id = id
        self.nome = nome
        self.data_de_nascimento = data_de_nascimento

    def __repr__(self):
        return f"<Proprietario {self.id}: {self.nome}, nascida(o) em {self.data_de_nascimento}>"


class Aluguel(db.Model):
    __tablename__ = 'Alugueis'

    id = db.Column(db.Integer, primary_key = True)
    imovel = db.Column(db.Integer, db.ForeignKey('Imoveis.id'))
    proprietario = db.Column(db.Integer, db.ForeignKey('Proprietarios.id'))

    def init(self, id, imovel, proprietario):
        self.id = id,
        self.imovel = imovel,
        self.proprietario = proprietario

    def __repr__(self):
        return f"<Aluguel id: {self.id}, id imovel: {self.imovel}, id proprietario: {self.proprietario}."


class Contrato(db.Model):
    __tablename__ = 'Contratos'

    id = db.Column(db.Integer, primary_key = True)
    aluguel = db.Column(db.Integer, db.ForeignKey('Alugueis.id'))
    inquilino = db.Column(db.Integer, db.ForeignKey('Inquilinos.id'))

    def __init__(self, id, aluguel, inquilino):
        self.id = id,
        self.aluguel = aluguel,
        self.inquilino = inquilino

    def __repr__(self):
        return "<Contrato de Inquilino {self.inquilino} no Aluguel {self.aluguel}.>"

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, DateField
from wtforms.validators import InputRequired, Length

class FormImoveis(FlaskForm):
    logradouro = StringField('Logradouro', validators=[InputRequired()])
    cep = IntegerField('CEP', validators=[InputRequired()])
    bairro = StringField('Bairro', validators=[InputRequired()])
    cidade = StringField('Cidade', validators=[InputRequired()])

class FormProprietarios(FlaskForm):
    nome = StringField('Nome', validators=[InputRequired()])
    data_de_nascimento = DateField('Data de Nascimento',
                                   format='%d/%m/%Y',
                                   validators=[InputRequired()])

class FormInquilinos(FlaskForm):
    nome = StringField('Nome', validators=[InputRequired()])
    data_de_nascimento = DateField('Data de Nascimento',
                                   format='%d/%m/%Y',
                                   validators=[InputRequired()])

class FormAlugueis(FlaskForm):
    imovel = IntegerField('Id do Imovel', validators=[InputRequired()])
    proprietario = IntegerField('Id do Proprietario', validators=[InputRequired()])

class FormContratos(FlaskForm):
    aluguel = IntegerField('Id do Aluguel', validators=[InputRequired()])
    inquilino = IntegerField('Id do Inquilino', validators=[InputRequired()])

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from os import environ

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = environ.get('SQLALCHEMY_DATABASE_URI')
    app.config['SECRET_KEY'] = environ.get('SECRET_KEY')
    migrate = Migrate(app, db)

    db.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template, abort, url_for
from . import main, api
from .. import db
from .forms import FormImoveis, FormProprietarios, FormInquilinos, FormAlugueis, FormContratos


@main.route('/', methods=['GET'])
def handle_index():
    return render_template('index.html')

@main.route('/listar/<lista>', methods=['GET'])
def handle_listar_itens(lista):
    opcoes = {
        'imoveis': api.handle_imoveis(),
        'proprietarios':api.handle_proprietarios(),
        'inquilinos': api.handle_inquilinos(),
        'alugueis': api.handle_alugueis(),
        'contratos': api.handle_contratos()
    }
    if lista in opcoes:
        itens = opcoes[lista]
        return render_template('listar_itens.html', lista = lista, itens = itens)
    else:
        abort(404)

@main.route('/listar/<lista>/<id>', methods=['GET'])
def handle_mostrar_item(lista, id):
    opcoes = {
        'imoveis': handle_imovel,
        'proprietarios': handle_proprietario,
        'inquilinos': handle_inquilino,
        'alugueis': handle_aluguel,
        'contratos': handle_contrato
    }
    if lista in opcoes:
        item = opcoes[lista](id)
        return render_template('mostrar_item.html', lista = lista, item = item)
    else:
        abort(404)

@main.route('/post/<lista>', methods=['GET'])
def handle_post_item(lista):
    templates = {
                 'imoveis': 'post_imoveis.html',
                 'proprietarios': 'post_proprietarios.html',
                 'inquilinos': 'post_inquilinos.html',
                 'alugueis': 'post_alugueis.html',
                 'contratos': 'post_contratos.html'
    }
    forms = {
                'imoveis': FormImoveis,
                'proprietarios': FormProprietarios,
                'inquilinos': FormInquilinos,
                'alugueis': FormAlugueis,
                'contratos': FormContratos
    }
    form = forms[lista]()
    return render_template(templates[lista], lista = lista, form = form)

app/templates/base.html
<html>
  <head>
    <!--<meta charset="ISO-8859-1">-->
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    {% block head %}
    <title>{% block title %}{% endblock %} - Cadastro Imobiliario</title>
    {% endblock %}
</head>
  <body>
    <nav>
        <a href="{{ url_for('main.handle_index') }}">Cadastro Imobiliario</a>
    </nav>
    <hr>
    {% block content %}
    {% endblock content %}
</body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block title %}Index{% endblock title %}
{% block head %}
    {{ super() }}
{% endblock head %}
{% block content %}
<h1>Cadastro Imobiliario</h1>
<h2>Listar Itens</h2>
<ul>
  <li><a href="{{ url_for('main.handle_listar_itens', lista='imoveis') }}">Imoveis</a></li>
  <li><a href="{{ url_for('main.handle_listar_itens', lista='inquilinos') }}">Inquilinos</a></li>
  <li><a href="{{ url_for('main.handle_listar_itens', lista='proprietarios') }}">Proprietarios</a></li>
  <li><a href="{{ url_for('main.handle_listar_itens', lista='alugueis') }}">Alugueis</a></li>
  <li><a href="{{ url_for('main.handle_listar_itens', lista='contratos') }}">Contratos</a></li>
</ul>
{% endblock content %}

app/templates/listar_itens.html
{% extends "base.html" %}
{% block title %}{{ lista.capitalize() }}{% endblock %}
{% block head %}
    {{ super() }}
{% endblock head %}
{% block content %}
<h1>{{ lista.capitalize() }}</h1>
  <p>Total: {{ itens['total'] }}</p>
  <ul>
  {% for item in itens[lista] %}
    <li>{{ item }}</li>
  {% endfor %}
  </ul>
{% endblock content %}

app/templates/mostrar_item.html
{% extends "base.html" %}
{% block title %}{{ lista.capitalize() }}{% endblock %}
{% block head %}
    {{ super() }}
{% endblock head %}
{% block content %}
<h1>{{ lista.capitalize() }}</h1>
<p>{{ item }}</p>
{% endblock content %}

app/templates/post_alugueis.html
{% extends "base.html" %}
{% block title %}Post {{ lista.capitalize() }}{% endblock %}
{% block head %}
{{ super() }}
{% endblock head %}
{% block content %}
<form method="POST" action="/alugueis">
  {{ form.csrf_token }}
    <p>
        {{ form.imovel.label }}
        {{ form.imovel }}
    </p>

    {% if form.imovel.errors %}
        <ul class="errors">
            {% for error in form.imovel.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <p>
        {{ form.proprietario.label }}
        {{ form.proprietario }}
    </p>

    {% if form.proprietario.errors %}
        <ul class="errors">
            {% for error in form.proprietario.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <input type="submit" value="Submit">
</form>
	
{% endblock content %}

app/templates/post_contratos.html
{% extends "base.html" %}
{% block title %}Post {{ lista.capitalize() }}{% endblock %}
{% block head %}
{{ super() }}
{% endblock head %}
{% block content %}
<form method="POST" action="/contratos">
  {{ form.csrf_token }}
    <p>
        {{ form.aluguel.label }}
        {{ form.aluguel }}
    </p>

    {% if form.aluguel.errors %}
        <ul class="errors">
            {% for error in form.aluguel.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <p>
        {{ form.inquilino.label }}
        {{ form.inquilino }}
    </p>

    {% if form.inquilino.errors %}
        <ul class="errors">
            {% for error in form.inquilino.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <input type="submit" value="Submit">
</form>
	
{% endblock content %}

app/templates/post_imovel.html
{% extends "base.html" %}
{% block title %}Post {{ lista.capitalize() }}{% endblock %}
{% block head %}
{{ super() }}
{% endblock head %}
{% block content %}
<form method="POST" action="/imoveis">
  {{ form.csrf_token }}
        <p>
            {{ form.logradouro.label }}
            {{ form.logradouro }}
        </p>

	{% if form.logradouro.errors %}
            <ul class="errors">
                {% for error in form.logradouro.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}

	<p>
            {{ form.cep.label }}
            {{ form.cep }}
        </p>

	{% if form.cep.errors %}
            <ul class="errors">
                {% for error in form.cep.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}

	<p>
            {{ form.bairro.label }}
            {{ form.bairro }}
        </p>

	{% if form.bairro.errors %}
            <ul class="errors">
                {% for error in form.bairro.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}

	<p>
            {{ form.cidade.label }}
            {{ form.cidade }}
        </p>

	{% if form.cidade.errors %}
            <ul class="errors">
                {% for error in form.cidade.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}

  <input type="submit" value="Submit">
</form>
	
{% endblock content %}

app/templates/post_inquilinos.html
{% extends "base.html" %}
{% block title %}Post {{ lista.capitalize() }}{% endblock %}
{% block head %}
{{ super() }}
{% endblock head %}
{% block content %}
<form method="POST" action="/inquilinos">
  {{ form.csrf_token }}
    <p>
        {{ form.nome.label }}
        {{ form.nome }}
    </p>

    {% if form.nome.errors %}
        <ul class="errors">
            {% for error in form.nome.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <p>
        {{ form.data_de_nascimento.label }}
        {{ form.data_de_nascimento }}
    </p>

    {% if form.data_de_nascimento.errors %}
        <ul class="errors">
            {% for error in form.data_de_nascimento.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <input type="submit" value="Submit">
</form>
	
{% endblock content %}

app/templates/post_item.html
{% extends "base.html" %}
{% block title %}Post {{ lista.capitalize() }}{% endblock %}
{% block head %}
{{ super() }}
{% endblock head %}
{% block content %}
<form method="POST" action="/imoveis">
  {{ form.csrf_token }}
        <p>
            {{ form.logradouro.label }}
            {{ form.logradouro }}
        </p>

	{% if form.logradouro.errors %}
            <ul class="errors">
                {% for error in form.logradouro.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}

	<p>
            {{ form.cep.label }}
            {{ form.cep }}
        </p>

	{% if form.cep.errors %}
            <ul class="errors">
                {% for error in form.cep.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}

	<p>
            {{ form.bairro.label }}
            {{ form.bairro }}
        </p>

	{% if form.bairro.errors %}
            <ul class="errors">
                {% for error in form.bairro.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}

	<p>
            {{ form.cidade.label }}
            {{ form.cidade }}
        </p>

	{% if form.cidade.errors %}
            <ul class="errors">
                {% for error in form.cidade.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}

  <input type="submit" value="Submit">
</form>
	
{% endblock content %}

app/templates/post_proprietario.html
{% extends "base.html" %}
{% block title %}Post {{ lista.capitalize() }}{% endblock %}
{% block head %}
{{ super() }}
{% endblock head %}
{% block content %}
<form method="POST" action="/proprietarios">
  {{ form.csrf_token }}
    <p>
        {{ form.nome.label }}
        {{ form.nome }}
    </p>

    {% if form.nome.errors %}
        <ul class="errors">
            {% for error in form.nome.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <p>
        {{ form.data_de_nascimento.label }}
        {{ form.data_de_nascimento }}
    </p>

    {% if form.data_de_nascimento.errors %}
        <ul class="errors">
            {% for error in form.data_de_nascimento.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <input type="submit" value="Submit">
</form>
	
{% endblock content %}